# Generated by Django 4.1.1 on 2022-09-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_mngmnt_sys_app', '0002_students_session_end_year_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceRepaort',
            new_name='AttendanceReport',
        ),
    ]
