# Generated by Django 4.1.1 on 2022-10-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_mngmnt_sys_app', '0004_alter_attendance_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackstudent',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
