# Generated by Django 4.1.1 on 2022-10-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_mngmnt_sys_app', '0005_rename_create_at_feedbackstudent_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackstaff',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
