# Generated by Django 4.1.1 on 2022-09-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_mngmnt_sys_app', '0005_alter_students_session_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='session_end_year',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='students',
            name='session_start_year',
            field=models.DateField(blank=True, default=''),
        ),
    ]
