# Generated by Django 4.1.1 on 2022-09-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_mngmnt_sys_app', '0007_alter_students_session_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
    ]
