# Generated by Django 4.1.1 on 2022-10-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_mngmnt_sys_app', '0007_alter_leavereportstudent_leave_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavereportstaff',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='leavereportstudent',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
