# Generated by Django 4.1.1 on 2022-09-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_mngmnt_sys_app', '0008_alter_staffs_created_at_alter_staffs_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='session_end_year',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='students',
            name='session_start_year',
            field=models.DateField(default=None),
        ),
    ]
