# Generated by Django 4.1.1 on 2022-09-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_mngmnt_sys_app', '0009_alter_staffs_created_at_alter_staffs_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='session_end_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='session_start_year',
            field=models.DateField(),
        ),
    ]
